### ISSUE TITLE
Street Lights Out: College Ave 38th - 42nd 

### ISSUE THREAD

**Issue by cmarburger08** [meridian-kessler/Infrastructure#14]
@DominicBM  - please feel free to drop in your correspondence to date here! I'll be sure to update following my meeting TODAY!

**Comment by cmarburger08** [comment]
@DominicBM 
Discussed at length with IPL today. Even with a fully operational Red Line, the issues lie beneath the surface with hundreds of yards of severed cables that need repair. At this time, IPL is negotiating with IndyGo and their contractors for reimbursement of the cost of repairs while meeting with DPW to push through permits and work orders to execute the work; however, the number of permits needed and the scale is overwhelming DPW and a workaround/solution for the arduous permitting process is needing. 

I am working on securing hundreds of solar-powered yard lights for neighbors by next week. Please standby on those efforts and do not announce until I have more concrete plans.

**Comment by cmarburger08** [comment]
Lights have been securred/ordered from Sullivan's Hardware and will be in hand early next week. Once received, we can publicize and have a party where we put them all out! :)

**Comment by DominicBM** [comment]
For the historical record, here is my email exchange with IndyGo (Jennifer Pyrz), starting 8/2:

> ---------- Forwarded message ---------
> From: Jennifer Pyrz <jpyrz@hntb.com>
> Date: Tue, Aug 20, 2019 at 12:01 PM
> Subject: RE: College Ave street lights
> To: Dominic Byrd-McDevitt <zone4@mkna.org>
> 
> Thanks for the heads up on that, Dominc.  We will keep an eye on it and make sure the work is getting done.  The problem is, admittedly,related to the Red Line construction… but our contractors are reliant upon IPL to do the work to actually get the lights back on.
> Jennifer Pyrz, PERed Line Construction Management Team Email jpyrz@hntb.comOffice (317) 917-5322    GoogleVoice / Mobile: (317) 983-4230 www.indygored.com
> 
> 

> From: Dominic Byrd-McDevitt [mailto:zone4@mkna.org] 
> > Sent: Tuesday, August 20, 2019 11:57 AM
> > To: Jennifer Pyrz <jpyrz@HNTB.com>
> > Subject: Re: College Ave street lights
> > Thanks, Jennifer! I will certainly pass that on. I think in this case IPL has been communicating poorly. They told residents they had no information about when the lights would come on because it was related to Red Line construction—without mentioning they were the ones performing the work themselves. The lights on a major street went out without warning and have stayed dark for weeks without any update to residents. One resident in particular who lives right on College expressed a lot of ill will towards the Red Line project as a whole due to this. I know this is not all under your control, so thanks for getting back to me!
> > Dominic 
> 
>

**Comment by DominicBM** [comment]
Also, here are other resident reports (that I am aware of from Facebook). These are all from the Zone 2 group.

First reported in March, 2019 to MAC (no number given on Facebook):

<img width="449" alt="Screen Shot 2019-09-11 at 4 06 56 PM" src="https://user-images.githubusercontent.com/2243767/64731169-a4746400-d4ae-11e9-9e5c-19ac4af09621.png">

On July 17, 2019, Jared Hall states lights have been out for months and he has filed 4 reports with IPL with no replies:

<img width="448" alt="Screen Shot 2019-09-11 at 4 07 42 PM" src="https://user-images.githubusercontent.com/2243767/64731366-151b8080-d4af-11e9-95af-0c85d87e977a.png">

On July 26, Jared posts screenshots of Facebook messages with IPL customer service where they say for the first time it is due to Red Line.

<img width="449" alt="Screen Shot 2019-09-11 at 4 08 28 PM" src="https://user-images.githubusercontent.com/2243767/64731442-3aa88a00-d4af-11e9-98bd-b7ef6cb1b411.png">

On August 2, I email IndyGo (above). On Aug. 20, Jennifer Pyrz responded (and I also shared her response on Facebook).

On September 4, 2019, RTV posted a news article about it: https://www.theindychannel.com/news/working-for-you/street-lights-out-along-college-avenue-because-of-indygo-red-line-construction

**Comment by DominicBM** [comment]
> @DominicBM
> Discussed at length with IPL today. Even with a fully operational Red Line, the issues lie beneath the surface with hundreds of yards of severed cables that need repair. At this time, IPL is negotiating with IndyGo and their contractors for reimbursement of the cost of repairs while meeting with DPW to push through permits and work orders to execute the work; however, the number of permits needed and the scale is overwhelming DPW and a workaround/solution for the arduous permitting process is needing.
> 
> I am working on securing hundreds of solar-powered yard lights for neighbors by next week. Please standby on those efforts and do not announce until I have more concrete plans.

Thanks for your work on this, @cmarburger08! I think people will be really happy to know what is going on, as well well as to hear about your stopgap measures! (Too bad DPW/IndyGo can't pay us back.)

**Comment by cmarburger08** [comment]
We’re not paying for it! :)

**Comment by DominicBM** [comment]
Wow, way to go!

**Comment by cmarburger08** [comment]
Light installed - neighbors excited and receptive. 

According to IPL, they have ordered materials and we should see repairs in the coming weeks!

**Comment by DominicBM** [comment]
According to Facebook, the lights came back on last night!

![IMG_5496](https://user-images.githubusercontent.com/2243767/66147017-eb500800-e5db-11e9-97c6-2f670d42c981.PNG)

**Comment by JdfMKNA2019** [comment]
Test comment
